customCommands:
  - key: "U"
    command: "git pull && git submodule update --init --recursive"
    context: "global"
    description: "Update submodules"
    loadingText: "Updating Submodules..."
    output: log
